language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - DEPENDENCIES="" COVERAGE="yes"
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer update --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/behat
  - if [[ $COVERAGE == yes ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml; fi
  - if [[ $COVERAGE != yes ]]; then vendor/bin/phpunit; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi
